### ISSUE TITLE
Connection:close header for all HTTP responses

### ISSUE THREAD

**Issue by EugeneChung** [EOSIO/fc#10]
By 4d8b5e571fd4b620816cf62171b5f056591157fb, all of the HTTP responses by nodeos includes "Connection: close" header.
It means all DApps which use the common HTTP/1.1 libraries are forced to do TCP connect for every HTTP request, which can cause significant performance degradation and resource exhaustion(TCP port, ...).

> added "Connection: close" to websocketpps http request handling as "keep-alive" is the default for HTTP/1.1 and it was confusing Beast

I don't know what the problem was caused by Beast, but setting "Connection: close" header must be done specifically not generally.

**Comment by wanderingbort** [comment]
The issue is that this version of websocketpp is producing an invalid HTTP protocol response.

https://github.com/EOSIO/fc/blob/62a19a758682679e3de27d956986eaf8b016465d/vendor/websocketpp/websocketpp/impl/connection_impl.hpp#L1318

Sets the protocol for the response to `HTTP/1.1`.  As per spec, if the `Connection:` header is not present in `HTTP/1.1` then the default is `keep-alive`.

However, this version of websocketpp would terminate the socket connection after sending any HTTP response here:

https://github.com/EOSIO/fc/blob/62a19a758682679e3de27d956986eaf8b016465d/vendor/websocketpp/websocketpp/impl/connection_impl.hpp#L1426

As a result, this response while accepted by most clients as a timeout of the `keep-alive` was resulting in boost BEAST based clients (and some others) hanging until their internal times were reached.  

As we have no internal support for keeping the connection alive, the appropriate HTTP/1.1 response would include a `Connection: close` headers.
